# Generated by Django 4.0.4 on 2022-05-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
